### ISSUE TITLE
All emails have german salutation

### ISSUE THREAD

**Issue by JoshuaBehrens** [nfxmedia/ekomi#1]
I really appreciate that you put your code on github and open it up for the community to participate. I am fiddling around with this plugin and saw these lines of code:
https://github.com/nfxmedia/ekomi/blob/ef93d90e0043a3eb7ed5e5abdf3bbc9f5b43a842/backend/NFXeKomiInterface/NFXeKomiManager.php#L424-L430

It looks to me that neither custom salutations will work nor that there is support for non-german salutations in emails.

**Comment by nfx702** [comment]
Thanks for the update and the appreciation. It's true - that's not ideal. Feel free to suggest a better solution and we will take care in the next release.

**Comment by nfx702** [comment]
@JoshuaBehrens Thank you for taking part on this project. We really appreciate it.
